### PR TITLE
made modification needed to fix strings bug

### PR DESCRIPTION
**Pull request by ctevans**
I don't know why it says I changed more than one file.

._. was a simple strings bug fix. Reforked repo and I just.. _facedesks_

### CODE REVIEW

**Comment by ctevans** [comment]
Going through the code in the ratings.java file there was a non-controller method used to access the user database. 

I am not sure why it was like that, but I changed it back to master controller. However I am tempted to just gut this and move it into a controller.

**Comment by ctevans** [comment]
Made the change so the controller has the DB stuff.

**Comment by FancifulEight** [comment]
I think most of that may have been done?

**Comment by FancifulEight** [comment]
After a merge has been done, I think your database controller stuff needs to be pushed

**Comment by FancifulEight** [comment]
Ignore that

**Pull request closed without merging**
