### PR TITLE
Refactoring

### PR DESCRIPTION
**Pull request by FancifulEight**
E-V-E-R-Y-W-H-E-R-E

### CODE REVIEW

**Comment by nwoeanhinnogaehr** [comment]
formatting not refactoring.

**Comment by FancifulEight** [comment]
No, I moved some code, reformatted some code and moved some methods into the controller

**Comment by FancifulEight** [comment]
Hence, refactoring

**Comment by nwoeanhinnogaehr** [comment]
oh whoops, didn't notice

**Pull request merged**
